### PR TITLE
[WIP] Auth and permissions bug

### PR DESCRIPTION
**Pull request by pietgeursen**
Heeeeyyy @ahdinosaur,

Would love to know if the failing tests here should actually pass. I THINK they're right from how I read the docs but would love your thoughts.

:)

### CODE REVIEW

**Comment by ahdinosaur** [comment]
hmm, you're right. `authenticate` isn't being called in your test because it's called when the WebSocket connects, which isn't happening in your test because you're using just the generic streams. if you start a server with `vas.listen` and connect with `vas.connect`, it should work. i'm not sure what to do about this, in my latest [`http` branch](https://github.com/ahdinosaur/vas/tree/http) this problem is even worse (there are no generic streams, just http clients and servers).

**Comment by pietgeursen** [comment]
Yeah, I worked that out about authenticate getting called after I made the PR.

But I think there's still a problem with permissions not getting called with the id set by authenticate.
Hmmm, been studying the code but not sure how to fix that up....

**Comment by ahdinosaur** [comment]
i should say, i do know _about_ the proper solution: represent multiplexed RPC as a duplex pull stream, where HTTP and WebSocket connections are duplex streams that wrap the generic ones. but implementation wise, it's a tough cookie, will need some time to think about it (when i'm not working on a busy contract, hehe).

thanks for these tests by the way! :cake:

**Comment by ahdinosaur** [comment]
oh yeah, that makes sense, the permissions function isn't being called with `this`: https://github.com/ssbc/muxrpc/blob/master/local-api.js#L35. i was actually planning on migrating from using `muxrpc`'s permissions to using [`aspects`](https://github.com/ahdinosaur/aspects), which you can do already manually.

**Comment by pietgeursen** [comment]
Ooooh aspects are great!

**Pull request closed without merging**
